# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.URLField(blank=True, default=''),
        ),
    ]
