# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='debateexpertise',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
